onlyBuiltDependencies:
  - '@sentry/cli'
  - sharp
verifyDepsBeforeRun: false
overrides:
  '@tiptap/core': 3.22.2
  '@tiptap/pm': 3.22.2
allowBuilds:
  '@sentry/cli': set this to true or false
  sharp: set this to true or false
